### PR TITLE
Bump versions + CDN

### PR DESCRIPTION
**Pull request by mauriciolauffer**
Bump dependencies version

Replace CDN by one with better caching. From https://openui5nightly.hana.ondemand.com to https://openui5.hana.ondemand.com

### CODE REVIEW

**Comment by akudev** [comment]
Definitely using openui5 is better (safer and faster) than using openui5nightly!
Just wait with merging until the regression worked around by https://github.com/UI5Lab/UI5Lab-browser/pull/13 is fixed again.

**Comment by mauriciolauffer** [comment]
Once merged, I'll create a PR for ui5lab-central which relies on this one  ;)

**Comment by mauriciolauffer** [comment]
@Michadelic 
For some unknown reason, the package wasn't updated into NPM. Current tag is 1.0.2 from 6 months ago...

https://www.npmjs.com/package/ui5lab-browser

**Comment by Michadelic** [comment]
I just tried again and bumped the version to 1.1.1 (couldn't let this opportunity slip 👍)
Its odd, seems to be a caching issue on npmjs.org.

When you search for "ui5lab" and select the "ui5lab-browser" from the search suggestions, the new version is displayed. When you press F5 then it shows 1.0.2 again and the updates are hidden.

Lets see how the ui5lab-central project behaves.

Kind Regards,
Michael

**Comment by Michadelic** [comment]
Hi @mauriciolauffer 

i created two fixes on top of your change as async processing of library metadata loading was broken and did not work as expected anymore:
https://github.com/UI5Lab/UI5Lab-browser/commit/fe554ee3f4664b0600c50ee03f34275424ef8f86
https://github.com/UI5Lab/UI5Lab-browser/commit/6d5d19bbd998399712494d630846fb562bf4b316

PS: BlocklayoutCell regression still not fixed, i hard-coded the version again in the index.html file(s)

**Pull request merged**
